<a href="https://colab.research.google.com/github/fralibatero/BIBLIOTECA_ANALISIS_DATOS/blob/main/Laboratorio_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame**

In [7]:
import pandas as pd

datos = pd.DataFrame({
    'Nombre': ['Katalina', 'Francia', 'Gloria', 'Alicia', 'Moises', 'Clara', 'Jenny', 'Orlando'],
    'Profesion': ['Contador', 'Analista de Datos', 'Abogado', 'Medico', 'Enfermedra', 'Pediatra', 'Programador', 'Analista Web'],
    'Pais': ['Colombia', 'Brazil', 'España', 'Estados Unidos', 'Canada', 'Filandia', 'Alemania', 'Portugal']
})

df = pd.DataFrame(datos)
print(df)

     Nombre          Profesion            Pais
0  Katalina           Contador        Colombia
1   Francia  Analista de Datos          Brazil
2    Gloria            Abogado          España
3    Alicia             Medico  Estados Unidos
4    Moises         Enfermedra          Canada
5     Clara           Pediatra        Filandia
6     Jenny        Programador        Alemania
7   Orlando       Analista Web        Portugal


**Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las primeras 5 filas**

In [33]:

import pandas as pd

df = pd.read_csv('data.csv')
print(df.head())


   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [43]:
import pandas as pd

df = pd.read_json('data.json')
print(df.head())


   Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


**-	Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar un resumen estadístico de los datos.**

In [42]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(100, 8), columns=list('ABCDEFGH'))

print(df)


           A         B         C         D         E         F         G  \
0   0.926417  0.935167  0.022578  0.886185  0.592961  0.163531  0.974997   
1   0.927462  0.838365  0.800281  0.691833  0.033663  0.652846  0.344123   
2   0.887735  0.339978  0.862266  0.929035  0.624579  0.974550  0.140718   
3   0.973708  0.326989  0.703444  0.670677  0.317751  0.145487  0.778208   
4   0.375175  0.141709  0.851390  0.831444  0.772261  0.629728  0.949265   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.348006  0.339061  0.660338  0.969671  0.311151  0.256098  0.293773   
96  0.490715  0.547450  0.497283  0.210910  0.840332  0.392329  0.439757   
97  0.405986  0.207970  0.538041  0.993415  0.999042  0.173671  0.771309   
98  0.327074  0.333095  0.994332  0.418764  0.793159  0.359884  0.560054   
99  0.457179  0.612494  0.018997  0.161244  0.862683  0.469245  0.963995   

           H  
0   0.058420  
1   0.169642  
2   0.614389  
3   0.482223  
4   0.536621

# **Parte  2**
**El segundo ejercicio de práctica deberás realizar el código usando las funciones y bibliotecas Numpy en Python, con el respectivo grafico según los escenarios, escribir el respectivo código y mostrar el resultado, aplicar los temas vistos en clase**


***Ejercicio de práctica 2***
**Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo**

In [46]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
suma = np.sum(vector)
media = np.mean(vector)
maximo = np.max(vector)
print("La suma es:", suma)
print("La media es:", media)
print("El valor máximo es:", maximo)

La suma es: 55
La media es: 5.5
El valor máximo es: 10


**-	Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6** *texto en cursiva*

In [59]:
import numpy as np
array = np.zeros((3, 4))
print(array, "Vector incial","\n")
array = array.reshape(2, 6) # cambia la forma  de la matriz
print(array, "Vector Final","\n")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] Vector incial 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] Vector Final 



**-	Generar una matriz aleatoria de 3x3 y calcular su transpuesta.**


In [69]:
import numpy as np
vector = np.random.rand(3,3)
print(vector, "Vector incial","\n")
transpuesta = np.transpose(vector)
print(transpuesta, "Vector Final","\n")


[[0.72677879 0.78336444 0.73130459]
 [0.29750329 0.84039817 0.67534181]
 [0.53320609 0.95013669 0.71420489]] Vector incial 

[[0.72677879 0.29750329 0.53320609]
 [0.78336444 0.84039817 0.95013669]
 [0.73130459 0.67534181 0.71420489]] Vector Final 



**-	Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el array concatenado.**

> Añadir blockquote



In [77]:
import pandas as pd
import numpy as np
vector = np.array([1,2,3,4,5])
vector_2 = np.array([6,7,8,9, 10])
concatenado = np.concatenate((vector, vector_2))
print(vector, "Vector incial","\n")
print(vector_2, "Vector dos","\n")
print(concatenado, "Vector Concatenado","\n")


[1 2 3 4 5] Vector incial 

[ 6  7  8  9 10] Vector dos 

[ 1  2  3  4  5  6  7  8  9 10] Vector Concatenado 

